### ISSUE TITLE
Implement new design for widget

### ISSUE THREAD

**Issue by 3lvis** [bakkenbaeck/daylight-ios#100]
<img width="711" alt="screen shot 2017-03-16 at 11 30 18" src="https://cloud.githubusercontent.com/assets/1088217/23992095/fc4f756a-0a3b-11e7-922a-735dd8771fef.png">

**Comment by D-32** [comment]
Love it!

**Comment by 3lvis** [comment]
Doing some spring cleaning, please make a new issue if you still want to do this.
