### ISSUE TITLE
Notification button is not working well

### ISSUE THREAD

**Issue by marijnschilling** [bakkenbaeck/daylight-ios#56]
There's  delay on the changing from on to off, when i click on the bottom i don't get any feedback that something is actually happening. We should show feedback or make the change instant.

**Comment by 3lvis** [comment]
When you press the button we cancel all the old notifications first, I believe this is a quite heavy operation for the device, that's why there's a delay.

**Comment by 3lvis** [comment]
Fixed by @marijnschilling in https://github.com/bakkenbaeck/daylight-ios/pull/70.
